x<-sample(1:20,20)+rnorm(10,sd=2)
y<-x+rnorm(10,sd=3)
z<-(sample(1:20,20)/2)+rnorm(20,sd=5)
df<-data.frame(x,y,z)
plot(df[,1:3])
cor(df, method = "pearson")
cor(df[,1:3], method = "spearman")
cor.test(df$x, df$y, method = "pearson")
cor.test(df$x, df$y, method = "spearman")
m1<-lm(mpg~cyl,data=mtcars)
summary(m1)
par(mfrow=c(2,2))
plot(m1)